export enum RSSSourceType {
    SOCIAL_MEDIA = 'social-media', // 社交媒体"
    NEW_MEDIA = 'new-media', // 新媒体"
    TRADITIONAL_MEDIA = 'traditional-media', // 传统媒体"
    BBS = 'bbs', // 论坛"
    BLOG = 'blog', // 博客"
    PROGRAMMING = 'programming', // 编程"
    DESIGN = 'design', // 设计"
    LIVE = 'live', // 直播"
    MULTIMEDIA = 'multimedia', // 音视频"
    PICTURE = 'picture', // 图片"
    ANIME = 'anime', // 二次元"
    PROGRAM_UPDATE = 'program-update', // 程序更新"
    UNIVERSITY = 'university', // 大学通知"
    FORECAST = 'forecast', // 预报预警"
    TRAVEL = 'travel', // 出行旅游"
    SHOPPING = 'shopping', // 购物"
    GAME = 'game', // 游戏"
    READING = 'reading', // 阅读"
    GOVERNMENT = 'government', // 政务消息"
    STUDY = 'study', // 学习"
    JOURNAL = 'journal', // 科学期刊"
    FINANCE = 'finance', // 金融"
    OTHER = 'other', // 其他"
}
